# Generated by Django 5.1.3 on 2024-11-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_patient_emergency_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='city',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='state',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='doctor.patient'),
        ),
    ]
