# Generated by Django 5.1.3 on 2024-11-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_remove_prescription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(choices=[('once_daily', 'Once Daily'), ('twice_daily', 'Twice Daily'), ('three_times', 'Three Times Daily'), ('four_times', 'Four Times Daily'), ('every_morning', 'Every Morning'), ('every_evening', 'Every Evening'), ('as_needed', 'As Needed'), ('weekly', 'Weekly')], default='once_daily', max_length=100),
        ),
    ]
