# Generated by Django 5.1.3 on 2024-12-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
